### ISSUE TITLE
Dashboard Buttons

### ISSUE THREAD

**Issue by samaralock** [FrancLo92/ExpenseManager_Prototype#1]
For some reason I can't seem to work out why the dashboard buttons aren't working. Not sure if it's just me, but I tried both my branch and Francesco's and neither of them seem to be clickable in the emulator. But the links are all fine in the menu bar.

**Comment by FrancLo92** [comment]
Hi Samara, i deployed your branch onto my android phone and it is working fine. I am able to click on the dashboard buttons and navigate into both Request Appointment and Locate Us page. My branch also is working fine and i am able to navigate into other pages from the dashboard buttons.

**Comment by samaralock** [comment]
Okay. I don't know what was going on, they weren't working the other day. But I just checked again and now they are. I guess it was an issue at my end. 😆
